In [1]:
from sklearn.datasets import make_multilabel_classification
# from bls2 import broadnet
import bls1,bls3
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from skmultilearn.dataset import load_dataset
from skmultilearn.dataset import available_data_sets
from sklearn.metrics import accuracy_score,hamming_loss,f1_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from random import seed
from random import randrange,random
from csv import reader
import bagging1
from sklearn.ensemble import RandomForestClassifier

D:\anaconda3\envs\openne\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
set([x[0] for x in available_data_sets().keys()])

{'Corel5k',
 'bibtex',
 'birds',
 'delicious',
 'emotions',
 'enron',
 'genbase',
 'mediamill',
 'medical',
 'rcv1subset1',
 'rcv1subset2',
 'rcv1subset3',
 'rcv1subset4',
 'rcv1subset5',
 'scene',
 'tmc2007_500',
 'yeast'}

In [3]:
bls = bls3.broadnet(maptimes = 10,
               enhencetimes = 10,
               map_function = 'tanh',
               enhence_function = 'tanh',
               batchsize = 'auto',
               reg = 0.001)

In [4]:
bagging_net=bagging1.bagging_net(10,bls,True)

In [16]:
X_train, y_train, feature_names, label_names = load_dataset('scene', 'train')
X_test, y_test, _, _ = load_dataset('scene', 'test')
# X_train=X_train.toarray()
# y_train=y_train.toarray()
# X_test=X_test.toarray()
# y_test=y_test.toarray()
# X_train=X_train[:,1:]
# X_test=X_test[:,1:]
# X_train=pd.DataFrame(X_train.toarray()).drop(0,axis=1)
# X_test=pd.DataFrame(X_test.toarray()).drop(0,axis=1)

scene:train - exists, not redownloading
scene:test - exists, not redownloading


In [6]:
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(1211, 294) (1211, 6) (1196, 294) (1196, 6)


In [7]:
X_train

<1211x294 sparse matrix of type '<class 'numpy.float64'>'
	with 351805 stored elements in LInked List format>

In [8]:
bagging_net.fit(X_train,y_train)

number of mapping nodes 2940, number of enhence nodes 2940
mapping nodes maxvalue 1.0 minvalue -1.0 
enhence nodes maxvalue 0.99995 minvalue -0.99995 
number of mapping nodes 2940, number of enhence nodes 2940
mapping nodes maxvalue 1.0 minvalue -1.0 
enhence nodes maxvalue 0.99987 minvalue -0.9999 
number of mapping nodes 2940, number of enhence nodes 2940
mapping nodes maxvalue 1.0 minvalue -1.0 
enhence nodes maxvalue 0.99995 minvalue -0.99997 
number of mapping nodes 2940, number of enhence nodes 2940
mapping nodes maxvalue 1.0 minvalue -1.0 
enhence nodes maxvalue 0.99984 minvalue -0.99998 
number of mapping nodes 2940, number of enhence nodes 2940
mapping nodes maxvalue 1.0 minvalue -1.0 
enhence nodes maxvalue 0.99993 minvalue -0.99994 
number of mapping nodes 2940, number of enhence nodes 2940
mapping nodes maxvalue 1.0 minvalue -1.0 
enhence nodes maxvalue 0.99994 minvalue -0.99988 
number of mapping nodes 2940, number of enhence nodes 2940
mapping nodes maxvalue 1.0 minvalue 

In [9]:
predition=bagging_net.predict(X_test)
print(accuracy_score(y_pred=predition,y_true=y_test))
print(hamming_loss(y_pred=predition,y_true=y_test))
print(f1_score(y_pred=predition,y_true=y_test,average='micro'))

[[3.8167671  0.         0.         0.         2.46633377 0.        ]
 [5.14781069 1.83727139 0.         0.         0.         0.99286854]
 [6.95397331 0.         0.         1.17703035 7.17610144 0.        ]
 ...
 [0.         0.         0.         0.         0.         9.11365966]
 [2.83737457 0.         1.47346523 0.         2.46633377 3.80995132]
 [2.15167135 0.         0.99286854 0.         0.84440285 6.40775058]]
0.5610367892976589
0.10381828316610925
0.7159740754860846


In [10]:
bls.fit(X_train,y_train)
predition=bls.predict(X_test)
print(accuracy_score(y_pred=predition,y_true=y_test))
print(hamming_loss(y_pred=predition,y_true=y_test))
print(f1_score(y_pred=predition,y_true=y_test,average='micro'))

number of mapping nodes 2940, number of enhence nodes 2940
mapping nodes maxvalue 1.0 minvalue -1.0 
enhence nodes maxvalue 0.99992 minvalue -0.99998 
0.4498327759197324
0.12123745819397994
0.6116071428571429


In [11]:

predition=bagging_net.bls_net[0].predict(X_test)
print(accuracy_score(y_pred=predition,y_true=y_test))
print(hamming_loss(y_pred=predition,y_true=y_test))
print(f1_score(y_pred=predition,y_true=y_test,average='micro'))

0.32525083612040134
0.17224080267558528
0.5544340302811824


In [12]:
from skmultilearn.adapt import MLkNN,MLTSVM,MLARAM,BRkNNaClassifier
classifier = MLkNN()

# train
classifier.fit(X_train, y_train)

# predict
predition = classifier.predict(X_test)
print(accuracy_score(y_pred=predition,y_true=y_test))
print(hamming_loss(y_pred=predition,y_true=y_test))
print(f1_score(y_pred=predition,y_true=y_test,average='micro'))

0.6053511705685619
0.09002229654403568
0.7227467811158798


In [17]:
X_train=X_train.toarray()
y_train=y_train.toarray()
X_test=X_test.toarray()
y_test=y_test.toarray()

In [14]:


classifier = MLARAM()

# train
classifier.fit(X_train, y_train)

# predict
predition = classifier.predict(X_test)
print(accuracy_score(y_pred=predition,y_true=y_test))
print(hamming_loss(y_pred=predition,y_true=y_test))
print(f1_score(y_pred=predition,y_true=y_test,average='micro'))

0.5627090301003345
0.11970457079152731
0.696573648887319


In [18]:
classifier = DecisionTreeClassifier()

# train
classifier.fit(X_train, y_train)

# predict
predition = classifier.predict(X_test)
print(accuracy_score(y_pred=predition,y_true=y_test))
print(hamming_loss(y_pred=predition,y_true=y_test))
print(f1_score(y_pred=predition,y_true=y_test,average='micro'))

0.5117056856187291
0.15677257525083613
0.5678063772570112


In [19]:
classifier = RandomForestClassifier(n_estimators=100)

# train
classifier.fit(X_train, y_train)

# predict
predition = classifier.predict(X_test)
print(accuracy_score(y_pred=predition,y_true=y_test))
print(hamming_loss(y_pred=predition,y_true=y_test))
print(f1_score(y_pred=predition,y_true=y_test,average='micro'))

0.5225752508361204
0.09099777034559643
0.6791154791154791
